# Generated by Django 4.2.2 on 2023-06-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasiyni_ismi', models.CharField(max_length=100)),
                ('vasiyni_email', models.EmailField(max_length=250)),
                ('farzand_ismi', models.CharField(max_length=100)),
                ('farzand_yoshi', models.IntegerField(blank=True, null=True)),
                ('tel_nomer', models.IntegerField(blank=True, null=True)),
                ('xabar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
