# Generated by Django 4.2.2 on 2023-06-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
                ('kasbi', models.CharField(max_length=150)),
            ],
        ),
    ]
