# Generated by Django 4.2.2 on 2023-11-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTM', '0002_teacheraddmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAddModel',
        ),
    ]
