# Generated by Django 4.2.2 on 2023-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTM', '0004_kidermodel_kider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kider',
            name='manzil',
            field=models.CharField(choices=[('Toshkent sh', 'Toshkent sh'), ('Toshkent vil', 'Toshkent vil'), ('Andijon vil', 'Andijon vil'), ('Buxoro vil', 'Buxoro vil'), ("Farg'ona vil", "Farg'ona vil"), ('Jizzax vil', 'Jizzax vil'), ('Xorazm vil', 'Xorazm vil'), ('Namangan vil', 'Namangan vil'), ('Navoiy vil', 'Navoiy vil'), ('Qashqadaryo vil', 'Qashqadaryo vil'), ("Qoraqalpog'iston Res", "Qoraqalpog'iston Res"), ('Samarqand vil', 'Samarqand vil'), ('Sirdaryo vil', 'Sirdaryo vil'), ('Surxondaryo vil', 'Surxondaryo vil')], default=None, max_length=20),
        ),
    ]
