# Generated by Django 4.2.2 on 2023-11-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTM', '0010_alter_kider_manzil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kider',
            name='manzil',
            field=models.CharField(blank=True, choices=[('Toshkent', 'Toshkent'), ('Toshkent', 'Toshkent vil'), ('Andijon', 'Andijon vil'), ('Buxoro', 'Buxoro vil'), ("Farg'ona", "Farg'ona vil"), ('Jizzax', 'Jizzax vil'), ('Xorazm', 'Xorazm vil'), ('Namangan', 'Namangan vil'), ('Navoiy', 'Navoiy vil'), ('Qashqadaryo', 'Qashqadaryo vil'), ("Qoraqalpog'iston", "Qoraqalpog'iston Res"), ('Samarqand', 'Samarqand vil'), ('Sirdaryo', 'Sirdaryo vil'), ('Surxondaryo', 'Surxondaryo vil')], default='Toshkent sh', max_length=200, null=True),
        ),
    ]
