# Generated by Django 4.2.2 on 2023-11-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTM', '0011_alter_kider_manzil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kider',
            old_name='manzil',
            new_name='joylashuv',
        ),
    ]
